"""Physical constants used in the program"""
MIN_FUNDAMENTAL_FREQUENCY_HZ = 50 # Hz
MAX_FUNDAMENTAL_FREQUENCY_HZ = 500 # Hz

MIN_PERIOD_LENGTH_MSEC = 1000/MAX_FUNDAMENTAL_FREQUENCY_HZ
MAX_PERIOD_LENGTH_MSEC = 1000/MIN_FUNDAMENTAL_FREQUENCY_HZ

MIN_DECLINATION_TIME_MSEC = 0.2
MAX_DECLINATION_TIME_MSEC = 4.5

